// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtXOzdBmcdQXrRwoabqHs26v9bVg2dNT8',
    appId: '1:85965214764:web:101e9fbd4baff6321d2d89',
    messagingSenderId: '85965214764',
    projectId: 'iitkms-login',
    authDomain: 'iitkms-login.firebaseapp.com',
    storageBucket: 'iitkms-login.appspot.com',
    measurementId: 'G-3GKP9MRPHK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqLbhNlkUJk8JqEcy9Oc1PrKkylZn5TAA',
    appId: '1:85965214764:android:520ec034805389721d2d89',
    messagingSenderId: '85965214764',
    projectId: 'iitkms-login',
    storageBucket: 'iitkms-login.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2J19geeUSP4njSEPWNzuWQhBXoEAyq7s',
    appId: '1:85965214764:ios:3f51c8dc7dde37f91d2d89',
    messagingSenderId: '85965214764',
    projectId: 'iitkms-login',
    storageBucket: 'iitkms-login.appspot.com',
    iosBundleId: 'com.example.iitkms',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2J19geeUSP4njSEPWNzuWQhBXoEAyq7s',
    appId: '1:85965214764:ios:ebddfaa237bf330e1d2d89',
    messagingSenderId: '85965214764',
    projectId: 'iitkms-login',
    storageBucket: 'iitkms-login.appspot.com',
    iosBundleId: 'com.example.iitkms.RunnerTests',
  );
}
